- name: "install {{component}}"
  hosts: "{{component}}"
  become: yes
  roles:
  - "{{ component }}"

  tasks:
    - name: app setup
      ansible.builtin.import_role:
        name: common
        tasks_from: app-setup