- name: app setup
  import_role:
    name: common
    tasks_from: app-setup

- name: app setup
  import_role:
    name: common
    tasks_from: nodejs

- name: app setup
  import_role:
    name: common
    tasks_from: mongodbsetup