- name: "copy {{component}}"
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: "/etc/systemd/system/{{component}}.service"

- name: daemon reload and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted 
    enabled: yes  