- name: "copy {{comonent}}"
  ansible.builtin.copy:
    src: "{{comonent}}.service"
    dest: "/etc/systemd/system/{{comonent}}.service"

- name: daemon reload and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{comonent}}"
  ansible.builtin.service:
    name: "{{comonent}}"
    state: restarted 
    enabled: yes  